import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳' }
];

export const TRANSLATIONS = {
  // ==================== ENGLISH ====================
  en: {
    appTitle: 'AASHA',
    appSub: 'Rural Health Mission • Offline-First Digital Healthcare',
    offlineBadge: 'Works Fully Offline (IndexedDB)',
    onlineBadge: 'Online Mode',
    offlineMode: 'Offline Mode',
    allSynced: 'All Synced',
    pendingSync: 'Pending Sync',
    logout: 'Logout',
    resetSeed: 'Reset Seed Data',
    close: 'Close Window',
    save: 'Save Changes',
    cancel: 'Cancel',
    back: 'Back to Dashboard',
    searchPlaceholder: 'Search by name, ID, or phone...',
    viewDetails: 'View Details',
    openTimeline: 'Open Full Health Timeline',
    recordVitals: 'Record Field Vitals',
    scheduled: 'Scheduled',
    active: 'Active',
    months: 'Months',
    weeks: 'Weeks',
    days: 'Days',
    years: 'Years',

    // Clinical & Vitals
    bloodPressure: 'Blood Pressure (BP)',
    systolicBp: 'Systolic Blood Pressure',
    diastolicBp: 'Diastolic Blood Pressure',
    hemoglobin: 'Hemoglobin (Hb)',
    bloodSugar: 'Fasting Blood Sugar',
    weight: 'Weight (kg)',
    height: 'Height / Length (cm)',
    pulse: 'Pulse Rate (bpm)',
    fundalHeight: 'Fundal Height (cm)',
    temperature: 'Temperature (°C)',
    gestationalAge: 'Gestational Age',
    eddLabel: 'Estimated Delivery Date (EDD)',
    lmpLabel: 'Last Menstrual Period (LMP)',
    abhaId: 'ABHA ID',
    ifaTablets: 'Iron Folic Acid (IFA) Tablets',
    calciumTablets: 'Calcium Tablets',
    ancCheckup: 'ANC Prenatal Checkup',
    vaccination: 'Immunization / Vaccination',

    // Login Page
    loginTagline: 'Secure Healthcare Access Portal',
    loginHeading: 'Select Your Role to Sign In',
    loginSubheading: 'Click on your category below to enter your unique login credentials.',
    ashaTitle: 'ASHA Worker',
    ashaSubtitle: 'Frontline Field Portal',
    ashaDesc: 'Patient registration, field vitals recording, and daily home visits.',
    ashaBadge: 'Access: Registration + Vitals',
    doctorTitle: 'Medical Officer',
    doctorSubtitle: 'Doctor Clinical Portal',
    doctorDesc: 'High-risk triage queue, clinical data editing, diagnoses, and prescriptions.',
    doctorBadge: 'Access: Full Clinical Edit Permissions',
    patientTitle: 'Patient Portal',
    patientSubtitle: 'Individual Beneficiary Pass',
    patientDesc: 'Digital health pass, immunization in months, ANC schedule, and diet guide.',
    patientBadge: 'Access: One ID One Login (View-Only)',
    modalAshaTitle: 'ASHA Worker Sign In',
    modalAshaSubtitle: 'Enter your unique ASHA ID and Sub-Centre Security PIN',
    modalDoctorTitle: 'Medical Officer Sign In',
    modalDoctorSubtitle: 'Enter your unique Medical Registration Number and PHC PIN',
    modalPatientTitle: 'Patient Identification Sign In',
    modalPatientSubtitle: 'Enter your unique Patient ID / ABHA ID and Passcode (One ID = One Login)',
    idPlaceholderAsha: 'e.g. ASHA-VNS-04',
    idPlaceholderDoc: 'e.g. DOC-UP-88',
    idPlaceholderPatient: 'e.g. PAT-PW-101 or PAT-INF-201 or PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'Sign In to Portal',
    ashaLabel: 'ASHA Worker ID / Mobile Number *',
    pinLabelAsha: 'Sub-Centre Security PIN *',
    docLabel: 'Medical Registration Number *',
    pinLabelDoc: 'PHC Security Passcode *',
    patientLabel: 'Unique Patient ID / ABHA ID / Mobile *',
    pinLabelPatient: 'Patient Passcode / Security PIN *',
    footerText: 'AASHA (Maternova) • National Health Mission & Ministry of Health & Family Welfare',

    // ASHA Dashboard
    ashaWelcome: 'Welcome',
    assignedArea: 'Assigned Field Area',
    registerNewPatient: '+ Register New Patient',
    totalBeneficiaries: 'Total Beneficiaries',
    pregnantLady: 'Pregnant Lady',
    infants: 'Infant (0-5 Yrs)',
    elderlyPeople: 'Elderly People',
    viewAllRecords: 'View All Records',
    ancMaternalDetails: 'ANC 1-4 & Maternal Details',
    ageInMonthsVaccines: 'Age in Months & Vaccines',
    bpDiabetesDetails: 'BP & Blood Sugar Details',
    dailyReminders: 'Daily Action Checklist & Scheduled Reminders',
    popupPregnantTitle: 'Pregnant Mothers Cohort Details (Maternal Health)',
    popupInfantTitle: 'Infant & Child Cohort Details (Immunization & Growth)',
    popupElderlyTitle: 'Elderly Citizens Cohort Details (Geriatric & Chronic Care)',
    popupAllTitle: 'All Registered Village Beneficiaries',

    // Doctor Dashboard
    doctorWelcome: 'Medical Officer Dashboard',
    prioritySurveillance: 'Priority Surveillance',
    highRiskCases: 'High-Risk Cases',
    highRiskQueueTitle: 'High-Risk Patient Triage & Clinical Surveillance Queue',
    priorityReview: 'Priority Review Required',
    phcRegistryTitle: 'Primary Health Centre (PHC) Cohort Registry',
    phcRegistrySub: 'Doctor data editing, risk adjustment, and clinical order modifications (Doctor Full Edit Access).',
    editDataBtn: 'Edit Data',
    viewFileBtn: 'View File',
    doctorOrderLabel: "Doctor's Active Clinical Prescription & Order",

    // Patient Dashboard
    loggedInAs: 'Logged in as',
    verifiedSession: 'Verified Beneficiary Session',
    digitalHealthPass: 'Digital Health Pass (MCP / Ayushman Bharat)',
    age: 'Age',
    guardian: 'Guardian',
    location: 'Location',
    registeredAsha: 'Registered ASHA Worker',
    emergencyHelpline: 'Emergency Ambulance: 108 / 102',
    nextCheckupVaccine: 'Next Scheduled Checkup / Vaccine',
    latestHealthReadings: 'Latest Health Readings (Vitals)',
    doctorPrescriptionAdvice: "Doctor's Prescription & Advice",
    nutritiousFoods: 'Nutritious & Affordable Foods for',
    nutritiousFoodsSub: 'Locally accessible traditional ingredients recommended for your health condition.',
    prepTip: 'Preparation & Intake',
    counselingTip: 'ASHA Nutrition Counseling Tip',
    viewOnlyMode: 'View-Only Access Mode'
  },

  // ==================== HINDI (पूर्ण हिंदी अनुवाद) ====================
  hi: {
    appTitle: 'आशा (AASHA)',
    appSub: 'राष्ट्रीय ग्रामीण स्वास्थ्य मिशन • डिजिटल स्वास्थ्य प्रणाली',
    offlineBadge: 'पूर्णतः ऑफलाइन कार्यरत (इंटरनेट रहित)',
    onlineBadge: 'ऑनलाइन मोड',
    offlineMode: 'ऑफलाइन मोड',
    allSynced: 'सभी डेटा सुरक्षित रूप से सिंक',
    pendingSync: 'लंबित सिंक डेटा',
    logout: 'लॉगआउट',
    resetSeed: 'डेटा रीसेट करें',
    close: 'खिड़की बंद करें',
    save: 'बदलाव सुरक्षित करें',
    cancel: 'रद्द करें',
    back: 'डैशबोर्ड पर वापस जाएं',
    searchPlaceholder: 'नाम, मरीज आईडी या मोबाइल से खोजें...',
    viewDetails: 'विवरण देखें',
    openTimeline: 'संपूर्ण स्वास्थ्य इतिहास खोलें',
    recordVitals: 'स्वास्थ्य नाप दर्ज करें',
    scheduled: 'निर्धारित',
    active: 'सक्रिय',
    months: 'महीने',
    weeks: 'सप्ताह',
    days: 'दिन',
    years: 'वर्ष',

    // Clinical & Vitals Translated
    bloodPressure: 'रक्तचाप (ब्लड प्रेशर)',
    systolicBp: 'सिस्टोलिक रक्तचाप',
    diastolicBp: 'डायस्टोलिक रक्तचाप',
    hemoglobin: 'हीमोग्लोबिन स्तर',
    bloodSugar: 'खाली पेट रक्त शर्करा (शुगर)',
    weight: 'वजन (किलोग्राम)',
    height: 'ऊंचाई / लंबाई (सेमी)',
    pulse: 'नाड़ी गति (पल्स)',
    fundalHeight: 'गर्भ ऊंचाई (फंडल हाइट)',
    temperature: 'शारीरिक तापमान (°C)',
    gestationalAge: 'गर्भकालीन आयु',
    eddLabel: 'प्रसव की अनुमानित तिथि (EDD)',
    lmpLabel: 'अंतिम माहवारी तिथि (LMP)',
    abhaId: 'आभा स्वास्थ्य पहचान पत्र (ABHA ID)',
    ifaTablets: 'आयरन फोलिक एसिड (IFA) गोलियां',
    calciumTablets: 'कैल्शियम की गोलियां',
    ancCheckup: 'प्रसव पूर्व स्वास्थ्य जांच (ANC)',
    vaccination: 'टीकाकरण एवं प्रतिरक्षण',

    // Login Page
    loginTagline: 'सुरक्षित स्वास्थ्य लॉगिन पोर्टल',
    loginHeading: 'प्रवेश हेतु अपनी भूमिका चुनें',
    loginSubheading: 'विशिष्ट लॉगिन जानकारी दर्ज करने के लिए नीचे अपनी श्रेणी पर क्लिक करें।',
    ashaTitle: 'आशा कार्यकर्ता',
    ashaSubtitle: 'ग्रामीण स्वास्थ्य सहायिका पोर्टल',
    ashaDesc: 'मरीज पंजीकरण, फील्ड स्वास्थ्य जांच एवं दैनिक गृह भ्रमण प्रबंधन।',
    ashaBadge: 'अधिकार: मरीज पंजीकरण + स्वास्थ्य नाप',
    doctorTitle: 'चिकित्सा अधिकारी',
    doctorSubtitle: 'डॉक्टर क्लिनिकल पोर्टल',
    doctorDesc: 'उच्च जोखिम निगरानी, क्लिनिकल डेटा संपादन, रोग निदान एवं दवा पर्ची।',
    doctorBadge: 'अधिकार: पूर्ण डेटा संपादन अधिकार',
    patientTitle: 'मरीज पोर्टल',
    patientSubtitle: 'व्यक्तिगत स्वास्थ्य पास',
    patientDesc: 'डिजिटल स्वास्थ्य पत्र, महीनों में शिशु टीका/जांच एवं पौष्टिक आहार चार्ट।',
    patientBadge: 'अधिकार: एक आईडी एक लॉगिन (केवल दर्शन)',
    modalAshaTitle: 'आशा कार्यकर्ता प्रवेश',
    modalAshaSubtitle: 'अपनी विशिष्ट आशा आईडी एवं उप-स्वास्थ्य केंद्र सुरक्षा पिन दर्ज करें',
    modalDoctorTitle: 'चिकित्सा अधिकारी प्रवेश',
    modalDoctorSubtitle: 'अपना मेडिकल रजिस्ट्रेशन नंबर एवं अस्पताल सुरक्षा पिन दर्ज करें',
    modalPatientTitle: 'मरीज विशिष्ट पहचान पत्र प्रवेश',
    modalPatientSubtitle: 'अपनी मरीज आईडी / आभा आईडी एवं सुरक्षा पासकोड दर्ज करें (एक आईडी = एक लॉगिन)',
    idPlaceholderAsha: 'उदा. ASHA-VNS-04',
    idPlaceholderDoc: 'उदा. DOC-UP-88',
    idPlaceholderPatient: 'उदा. PAT-PW-101, PAT-INF-201, PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'पोर्टल में प्रवेश करें',
    ashaLabel: 'आशा आईडी / मोबाइल नंबर *',
    pinLabelAsha: 'उप-स्वास्थ्य केंद्र सुरक्षा पिन *',
    docLabel: 'चिकित्सक रजिस्ट्रेशन नंबर *',
    pinLabelDoc: 'पीएचसी सुरक्षा पासकोड *',
    patientLabel: 'विशिष्ट मरीज आईडी / आभा आईडी / मोबाइल *',
    pinLabelPatient: 'मरीज पासकोड / सुरक्षा पिन *',
    footerText: 'आशा (मातृनोवा) • राष्ट्रीय स्वास्थ्य मिशन एवं स्वास्थ्य एवं परिवार कल्याण मंत्रालय',

    // ASHA Dashboard
    ashaWelcome: 'स्वागत है',
    assignedArea: 'आवंटित कार्यक्षेत्र गाँव',
    registerNewPatient: '+ नया मरीज पंजीकृत करें',
    totalBeneficiaries: 'कुल पंजीकृत लाभार्थी',
    pregnantLady: 'गर्भवती महिला',
    infants: 'शिशु (0-5 वर्ष)',
    elderlyPeople: 'वरिष्ठ नागरिक',
    viewAllRecords: 'सभी रिकॉर्ड देखें',
    ancMaternalDetails: 'प्रसव पूर्व जांच (ANC 1-4) एवं मातृ सुरक्षा',
    ageInMonthsVaccines: 'महीनों में आयु एवं संपूर्ण टीकाकरण',
    bpDiabetesDetails: 'रक्तचाप एवं शुगर निगरानी विवरण',
    dailyReminders: 'दैनिक कार्य सूची एवं गृह भ्रमण अनुस्मारक',
    popupPregnantTitle: 'गर्भवती महिला दल विवरण (मातृ स्वास्थ्य)',
    popupInfantTitle: 'शिशु एवं बाल स्वास्थ्य दल विवरण (टीकाकरण एवं वृद्धि)',
    popupElderlyTitle: 'वरिष्ठ नागरिक दल विवरण (गैर-संचारी रोग एवं देखभाल)',
    popupAllTitle: 'सभी पंजीकृत ग्रामीण लाभार्थी सूची',

    // Doctor Dashboard
    doctorWelcome: 'चिकित्सा अधिकारी डैशबोर्ड',
    prioritySurveillance: 'प्राथमिकता निगरानी',
    highRiskCases: 'उच्च जोखिम मामले',
    highRiskQueueTitle: 'उच्च जोखिम मरीज प्राथमिकता एवं क्लिनिकल निगरानी कतार',
    priorityReview: 'तत्काल डॉक्टर समीक्षा आवश्यक',
    phcRegistryTitle: 'प्राथमिक स्वास्थ्य केंद्र (पीएचसी) मरीज रजिस्टर',
    phcRegistrySub: 'क्लिनिकल डेटा संपादन, जोखिम वर्गीकरण एवं डॉक्टर दवा पर्ची संशोधन अधिकार।',
    editDataBtn: 'डेटा संपादित करें',
    viewFileBtn: 'फाइल देखें',
    doctorOrderLabel: 'चिकित्सक का सक्रिय क्लिनिकल आदेश एवं दवा पर्ची',

    // Patient Dashboard
    loggedInAs: 'लॉगिन किया गया खाता',
    verifiedSession: 'प्रमाणित लाभार्थी सत्र',
    digitalHealthPass: 'डिजिटल स्वास्थ्य पत्र (मातृ एवं शिशु सुरक्षा / आयुष्मान भारत)',
    age: 'आयु (उम्र)',
    guardian: 'अभिभावक / संरक्षक',
    location: 'गाँव का स्थान',
    registeredAsha: 'पंजीकृत आशा कार्यकर्ता दीदी',
    emergencyHelpline: 'आपातकालीन सरकारी एम्बुलेंस: 108 / 102',
    nextCheckupVaccine: 'अगली निर्धारित स्वास्थ्य जांच / टीका',
    latestHealthReadings: 'हालिया स्वास्थ्य नाप एवं जांच',
    doctorPrescriptionAdvice: 'चिकित्सक की दवा एवं चिकित्सीय सलाह',
    nutritiousFoods: 'स्थानीय पौष्टिक, सुलभ एवं देसी आहार',
    nutritiousFoodsSub: 'आपके स्वास्थ्य के अनुकूल अनुशंसित पारंपरिक देसी खाद्य पदार्थ।',
    prepTip: 'बनाने की विधि एवं सेवन नियम',
    counselingTip: 'आशा दीदी पोषण परामर्श सलाह',
    viewOnlyMode: 'केवल दर्शन अधिकार मोड'
  },

  // ==================== TAMIL (முழு தமிழ் மொழிபெயர்ப்பு) ====================
  ta: {
    appTitle: 'ஆஷா (AASHA)',
    appSub: 'தேசிய கிராமப்புற சுகாதார இயக்கம் • டிஜிட்டல் சுகாதாரம்',
    offlineBadge: 'இணையமின்றி முழுமையாக இயங்கும்',
    onlineBadge: 'ஆன்லைன் பயன்முறை',
    offlineMode: 'ஆஃப்லைன் பயன்முறை',
    allSynced: 'அனைத்து தரவுகளும் பாதுகாப்பாக ஒத்திசைக்கப்பட்டது',
    pendingSync: 'நிலுவையில் உள்ள தரவு',
    logout: 'வெளியேறு',
    resetSeed: 'தொடக்க தரவுக்கு மீட்டமை',
    close: 'சாளரத்தை மூடு',
    save: 'மாற்றங்களைச் சேமிக்கவும்',
    cancel: 'ரத்து செய்',
    back: 'டாஷ்போர்டுக்குத் திரும்பு',
    searchPlaceholder: 'பெயர், நோயாளி ஐடி மூலம் தேடவும்...',
    viewDetails: 'விவரங்களைக் காண்க',
    openTimeline: 'முழு மருத்துவ வரலாற்றைத் திறக்கவும்',
    recordVitals: 'உடல் அளவீடுகளைப் பதிவு செய்',
    scheduled: 'திட்டமிடப்பட்டது',
    active: 'செயலில்',
    months: 'மாதங்கள்',
    weeks: 'வாரங்கள்',
    days: 'நாட்கள்',
    years: 'ஆண்டுகள்',

    // Clinical & Vitals Translated
    bloodPressure: 'இரத்த அழுத்தம் (BP)',
    systolicBp: 'சிஸ்டாலிக் இரத்த அழுத்தம்',
    diastolicBp: 'டயஸ்டாலிக் இரத்த அழுத்தம்',
    hemoglobin: 'ஹீமோகுளோபின் அளவு',
    bloodSugar: 'வெறும் வயிற்று சர்க்கரை அளவு',
    weight: 'எடை (கிலோ)',
    height: 'உயரம் / நீளம் (செ.மீ)',
    pulse: 'நாடித் துடிப்பு',
    fundalHeight: 'கருப்பை உயரம் (ஃபண்டல் உயரம்)',
    temperature: 'உடல் வெப்பநிலை (°C)',
    gestationalAge: 'கர்ப்பகால வயது',
    eddLabel: 'பிரசவ எதிர்பார்க்கப்படும் தேதி (EDD)',
    lmpLabel: 'கடைசி மாதவிடாய் தேதி (LMP)',
    abhaId: 'ஆபா டிஜிட்டல் சுகாதார அடையாள அட்டை',
    ifaTablets: 'இரும்பு சத்து மற்றும் ஃபோலிக் அமில மாத்திரைகள்',
    calciumTablets: 'கால்சியம் மாத்திரைகள்',
    ancCheckup: 'மகப்பேறுக்கு முந்தைய பரிசோதனை (ANC)',
    vaccination: 'தடுப்பூசி மற்றும் நோய்த்தடுப்பு',

    // Login Page
    loginTagline: 'பாதுகாப்பான சுகாதார நுழைவு போர்ட்டல்',
    loginHeading: 'உள்நுழைய உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    loginSubheading: 'உங்கள் தனித்துவ உள்நுழைவு விவரங்களை உள்ளிட கீழே கிளிக் செய்யவும்.',
    ashaTitle: 'ஆஷா பணியாளர்',
    ashaSubtitle: 'கிராம சுகாதார களப்பணியாளர் போர்ட்டல்',
    ashaDesc: 'நோயாளி பதிவு, கள அளவீடுகள் மற்றும் தினசரி இல்ல வருகை மேலாண்மை.',
    ashaBadge: 'அணுகல்: புதிய பதிவு + உடல் அளவீடுகள்',
    doctorTitle: 'மருத்துவ அதிகாரி',
    doctorSubtitle: 'மருத்துவர் மருத்துவ போர்ட்டல்',
    doctorDesc: 'அதிக ஆபத்து கண்காணிப்பு, தரவு திருத்தம் மற்றும் மருந்துக் குறிப்பு வழங்கல்.',
    doctorBadge: 'அணுகல்: முழு மருத்துவ திருத்த அனுமதி',
    patientTitle: 'நோயாளி போர்ட்டல்',
    patientSubtitle: 'தனிநபர் சுகாதார அட்டை',
    patientDesc: 'டிஜிட்டல் சுகாதார அட்டை, மாதங்களில் தடுப்பூசி மற்றும் உணவு வழிகாட்டி.',
    patientBadge: 'அணுகல்: ஒரு ஐடி ஒரு உள்நுழைவு (பார்வைக்கு மட்டும்)',
    modalAshaTitle: 'ஆஷா பணியாளர் உள்நுழைவு',
    modalAshaSubtitle: 'உங்கள் ஆஷா ஐடி மற்றும் துணை மைய பாதுகாப்பு பின்னை உள்ளிடவும்',
    modalDoctorTitle: 'மருத்துவ அதிகாரி உள்நுழைவு',
    modalDoctorSubtitle: 'உங்கள் பதிவு எண் மற்றும் மருத்துவமனை கடவுச்சொல்லை உள்ளிடவும்',
    modalPatientTitle: 'நோயாளி தனித்துவ அடையாள உள்நுழைவு',
    modalPatientSubtitle: 'உங்கள் நோயாளி ஐடி / ஆபா ஐடி மற்றும் கடவுக்குறியீட்டை உள்ளிடவும்',
    idPlaceholderAsha: 'எ.கா. ASHA-VNS-04',
    idPlaceholderDoc: 'எ.கா. DOC-UP-88',
    idPlaceholderPatient: 'எ.கா. PAT-PW-101, PAT-INF-201, PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'போர்ட்டலில் நுழைக',
    ashaLabel: 'ஆஷா ஐடி / மொபைல் எண் *',
    pinLabelAsha: 'துணை மைய பாதுகாப்பு பின் *',
    docLabel: 'மருத்துவ பதிவு எண் *',
    pinLabelDoc: 'பாதுகாப்பு கடவுக்குறியீடு *',
    patientLabel: 'தனித்துவ நோயாளி ஐடி / ஆபா ஐடி *',
    pinLabelPatient: 'பாதுகாப்பு கடவுக்குறியீடு *',
    footerText: 'ஆஷா • தேசிய சுகாதார இயக்கம் & சுகாதார மற்றும் குடும்ப நல அமைச்சகம்',

    // ASHA Dashboard
    ashaWelcome: 'வரவேற்கிறோம்',
    assignedArea: 'ஒதுக்கப்பட்ட கிராம பகுதி',
    registerNewPatient: '+ புதிய நோயாளியைப் பதிவுசெய்க',
    totalBeneficiaries: 'மொத்த பயனாளிகள்',
    pregnantLady: 'கர்ப்பிணிப் பெண்',
    infants: 'குழந்தை (0-5 ஆண்டுகள்)',
    elderlyPeople: 'முதியவர்கள்',
    viewAllRecords: 'அனைத்து பதிவுகளையும் காண்க',
    ancMaternalDetails: 'கர்ப்ப பரிசோதனை (ANC 1-4) & தாய்மை பாதுகாப்பு',
    ageInMonthsVaccines: 'மாதங்களில் வயது & முழுமையான தடுப்பூசி',
    bpDiabetesDetails: 'இரத்த அழுத்தம் & சர்க்கரை கண்காணிப்பு',
    dailyReminders: 'தினசரி பணிகள் மற்றும் இல்ல வருகைகள்',
    popupPregnantTitle: 'கர்ப்பிணித் தாய்மார்கள் பட்டியல் (தாய்மை நலம்)',
    popupInfantTitle: 'குழந்தைகள் நலம் மற்றும் வளர்ச்சிப் பட்டியல்',
    popupElderlyTitle: 'முதியோர் பராமரிப்பு மற்றும் நாள்பட்ட நோய் பட்டியல்',
    popupAllTitle: 'அனைத்து பதிவுசெய்யப்பட்ட கிராம பயனாளிகள்',

    // Doctor Dashboard
    doctorWelcome: 'மருத்துவ அதிகாரி டாஷ்போர்டு',
    prioritySurveillance: 'முன்னுரிமை கண்காணிப்பு',
    highRiskCases: 'அதிக ஆபத்து வழக்குகள்',
    highRiskQueueTitle: 'அதிக ஆபத்துள்ள நோயாளிகள் மருத்துவ கண்காணிப்பு வரிசை',
    priorityReview: 'மருத்துவரின் உடனடி ஆய்வு தேவை',
    phcRegistryTitle: 'ஆரம்ப சுகாதார நிலைய நோயாளி பதிவேடு',
    phcRegistrySub: 'மருத்துவ தரவு திருத்தம், ஆபத்து வகைப்பாடு மற்றும் மருந்துக் குறிப்பு மாற்றங்கள்.',
    editDataBtn: 'தரவை திருத்து',
    viewFileBtn: 'கோப்பைக் காண்க',
    doctorOrderLabel: 'மருத்துவரின் தற்போதைய மருந்துக் குறிப்பு மற்றும் ஆலோசனை',

    // Patient Dashboard
    loggedInAs: 'உள்நுழைந்துள்ள கணக்கு',
    verifiedSession: 'சரிபார்க்கப்பட்ட பயனாளி அமர்வு',
    digitalHealthPass: 'டிஜிட்டல் சுகாதார அட்டை (தாய்-சேய் பாதுகாப்பு அட்டை)',
    age: 'வயது',
    guardian: 'பாதுகாவலர் / கணவர்',
    location: 'கிராமம்',
    registeredAsha: 'பதிவுசெய்த ஆஷா பணியாளர் அக்கா',
    emergencyHelpline: 'அவசர ஆம்புலன்ஸ் உதவி: 108 / 102',
    nextCheckupVaccine: 'அடுத்த திட்டமிடப்பட்ட சோதனை / தடுப்பூசி',
    latestHealthReadings: 'சமீபத்திய உடல் அளவீடுகள்',
    doctorPrescriptionAdvice: 'மருத்துவரின் மருந்து மற்றும் அறிவுரைகள்',
    nutritiousFoods: 'பாரம்பரிய சத்தான கிராமப்புற உணவுகள்',
    nutritiousFoodsSub: 'உங்கள் ஆரோக்கியத்திற்காக பரிந்துரைக்கப்பட்ட சத்தான பாரம்பரிய உணவுகள்.',
    prepTip: 'செய்முறை மற்றும் உட்கொள்ளும் முறை',
    counselingTip: 'ஆஷா ஊட்டச்சத்து ஆலோசனை',
    viewOnlyMode: 'பார்வைக்கு மட்டுமே பயன்முறை'
  },

  // ==================== TELUGU (పూర్తి తెలుగు అనువాదం) ====================
  te: {
    appTitle: 'ఆశా (AASHA)',
    appSub: 'జాతీయ గ్రామీణ ఆరోగ్య మిషన్ • డిజిటల్ హెల్త్‌కేర్',
    offlineBadge: 'పూర్తిగా ఆఫ్‌లైన్‌లో పని చేస్తుంది (ఇంటర్నెట్ లేకుండా)',
    onlineBadge: 'ఆన్‌లైన్ మోడ్',
    offlineMode: 'ఆఫ్‌లైన్ మోడ్',
    allSynced: 'మొత్తం డేటా సురక్షితంగా సింక్ చేయబడింది',
    pendingSync: 'పెండింగ్ డేటా సింక్',
    logout: 'లాగౌట్',
    resetSeed: 'డేటా రీసెట్ చేయండి',
    close: 'విండో మూసివేయండి',
    save: 'మార్పులను భద్రపరచండి',
    cancel: 'రద్దు చేయండి',
    back: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి',
    searchPlaceholder: 'పేరు, రోగి ఐడీ ద్వారా శోధించండి...',
    viewDetails: 'వివరాలు చూడండి',
    openTimeline: 'పూర్తి ఆరోగ్య చరిత్రను తెరవండి',
    recordVitals: 'ఆరోగ్య పరీక్షలను నమోదు చేయండి',
    scheduled: 'షెడ్యూల్ చేయబడింది',
    active: 'యాక్టివ్',
    months: 'నెలలు',
    weeks: 'వారాలు',
    days: 'రోజులు',
    years: 'సంవత్సరాలు',

    // Clinical & Vitals Translated
    bloodPressure: 'రక్తపోటు (బీపీ)',
    systolicBp: 'సిస్టోలిక్ రక్తపోటు',
    diastolicBp: 'డయాస్టోలిక్ రక్తపోటు',
    hemoglobin: 'హిమోగ్లోబిన్ స్థాయి',
    bloodSugar: 'రక్తంలో చక్కెర (షుగర్)',
    weight: 'బరువు (కిలోలు)',
    height: 'ఎత్తు / పొడవు (సెం.మీ)',
    pulse: 'నాడి వేగం (పల్స్)',
    fundalHeight: 'గర్భాశయ ఎత్తు (ఫండల్ ఎత్తు)',
    temperature: 'శరీర ఉష్ణోగ్రత (°C)',
    gestationalAge: 'గర్భధారణ కాలం',
    eddLabel: 'ప్రసవ అంచనా తేదీ (EDD)',
    lmpLabel: 'చివరి ఋతుక్రమ తేదీ (LMP)',
    abhaId: 'ఆభా డిజిటల్ హెల్త్ ఐడీ (ABHA ID)',
    ifaTablets: 'ఐరన్ ఫోలిక్ యాసిడ్ (IFA) మాత్రలు',
    calciumTablets: 'కాల్షియం మాత్రలు',
    ancCheckup: 'ప్రసవ పూర్వ ఆరోగ్య తనిఖీ (ANC)',
    vaccination: 'టీకాలు మరియు రోగనిరోధకత',

    // Login Page
    loginTagline: 'సురక్షిత ఆరోగ్య లాగిన్ పోర్టల్',
    loginHeading: 'లాగిన్ కావడానికి మీ పాత్రను ఎంచుకోండి',
    loginSubheading: 'మీ ప్రత్యేక లాగిన్ వివరాలను నమోదు చేయడానికి క్రింద క్లిక్ చేయండి.',
    ashaTitle: 'ఆశా కార్యకర్త',
    ashaSubtitle: 'గ్రామీణ ఆరోగ్య సహాయకురాలి పోర్టల్',
    ashaDesc: 'రోగుల నమోదు, క్షేత్ర స్థాయి ఆరోగ్య పరీక్షలు మరియు రోజువారీ గృహ సందర్శనలు.',
    ashaBadge: 'యాక్సెస్: కొత్త నమోదు + ఆరోగ్య పరీక్షలు',
    doctorTitle: 'వైద్యాధికారి',
    doctorSubtitle: 'డాక్టర్ క్లినికల్ పోర్టల్',
    doctorDesc: 'అధిక ప్రమాద నిఘా, డేటా సవరణ, వ్యాధి నిర్ధారణ మరియు మందుల చీటీ.',
    doctorBadge: 'యాక్సెస్: పూర్తి సవరణ అనుమతి',
    patientTitle: 'రోగి పోర్టల్',
    patientSubtitle: 'వ్యక్తిగత ఆరోగ్య పాస్',
    patientDesc: 'డిజిటల్ హెల్త్ కార్డ్, నెలల్లో శిశువు టీకాలు మరియు పౌష్టికాహార చార్ట్.',
    patientBadge: 'యాక్సెస్: ఒక ఐడీ ఒక లాగిన్ (వీక్షణకు మాత్రమే)',
    modalAshaTitle: 'ఆశా కార్యకర్త లాగిన్',
    modalAshaSubtitle: 'మీ ఆశా ఐడీ మరియు ఉప-కేంద్రం సెక్యూరిటీ పిన్ నమోదు చేయండి',
    modalDoctorTitle: 'వైద్యాధికారి లాగిన్',
    modalDoctorSubtitle: 'మీ మెడికల్ రిజిస్ట్రేషన్ నంబర్ మరియు హాస్పిటల్ పిన్ నమోదు చేయండి',
    modalPatientTitle: 'రోగి విశిష్ట గుర్తింపు లాగిన్',
    modalPatientSubtitle: 'మీ రోగి ఐడీ / ఆభా ఐడీ మరియు పాస్‌కోడ్ నమోదు చేయండి (ఒక ఐడీ = ఒక లాగిన్)',
    idPlaceholderAsha: 'ఉదా. ASHA-VNS-04',
    idPlaceholderDoc: 'ఉదా. DOC-UP-88',
    idPlaceholderPatient: 'ఉదా. PAT-PW-101, PAT-INF-201, PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'పోర్టల్‌లోకి ప్రవేశించండి',
    ashaLabel: 'ఆశా ఐడీ / మొబైల్ నంబర్ *',
    pinLabelAsha: 'ఉప-కేంద్రం సెక్యూరిటీ పిన్ *',
    docLabel: 'మెడికల్ రిజిస్ట్రేషన్ నంబర్ *',
    pinLabelDoc: 'పీహెచ్‌సీ సెక్యూరిటీ పాస్‌కోడ్ *',
    patientLabel: 'ప్రత్యేక రోగి ఐడీ / ఆభా ఐడీ / మొబైల్ *',
    pinLabelPatient: 'పాస్‌కోడ్ / సెక్యూరిటీ పిన్ *',
    footerText: 'ఆశా • జాతీయ ఆరోగ్య మిషన్ మరియు ఆరోగ్య & కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ',

    // ASHA Dashboard
    ashaWelcome: 'స్వాగతం',
    assignedArea: 'కేటాయించిన గ్రామ ప్రాంతం',
    registerNewPatient: '+ కొత్త రోగిని నమోదు చేయండి',
    totalBeneficiaries: 'మొత్తం నమోదైన లబ్ధిదారులు',
    pregnantLady: 'గర్భిణీ స్త్రీ',
    infants: 'శిశువు (0-5 సంవత్సరాలు)',
    elderlyPeople: 'వృద్ధులు',
    viewAllRecords: 'అన్ని రికార్డులను చూడండి',
    ancMaternalDetails: 'ప్రసవ పూర్వ తనిఖీలు (ANC 1-4) & తల్లి రక్షణ',
    ageInMonthsVaccines: 'నెలల్లో వయస్సు & పూర్తి టీకాలు',
    bpDiabetesDetails: 'రక్తపోటు & షుగర్ నిఘా వివరాలు',
    dailyReminders: 'రోజువారీ పనులు & గృహ సందర్శన రిమైండర్లు',
    popupPregnantTitle: 'గర్భిణీ స్త్రీల బృందం వివరాలు (మాతృ ఆరోగ్యం)',
    popupInfantTitle: 'శిశు & బాలల ఆరోగ్య వివరాలు (టీకాలు & పెరుగుదల)',
    popupElderlyTitle: 'వృద్ధుల ఆరోగ్య వివరాలు (దీర్ఘకాలిక వ్యాధులు & సంరక్షణ)',
    popupAllTitle: 'మొత్తం నమోదైన గ్రామీణ లబ్ధిదారులు',

    // Doctor Dashboard
    doctorWelcome: 'వైద్యాధికారి డాష్‌బోర్డ్',
    prioritySurveillance: 'ప్రాధాన్యతా నిఘా',
    highRiskCases: 'అధిక ప్రమాద కేసులు',
    highRiskQueueTitle: 'అధిక ప్రమాద రోగుల పర్యవేక్షణ క్యూ',
    priorityReview: 'వైద్యుని తక్షణ సమీక్ష అవసరం',
    phcRegistryTitle: 'ప్రాథమిక ఆరోగ్య కేంద్రం రోగుల రిజిస్టర్',
    phcRegistrySub: 'క్లినికల్ డేటా సవరణ, ప్రమాద వర్గీకరణ మరియు మందుల మార్పు అనుమతి.',
    editDataBtn: 'డేటా సవరించండి',
    viewFileBtn: 'ఫైల్ చూడండి',
    doctorOrderLabel: 'వైద్యుని ప్రిస్క్రిప్షన్ మరియు సలహా',

    // Patient Dashboard
    loggedInAs: 'లాగిన్ అయిన ఖాతా',
    verifiedSession: 'ధృవీకరించబడిన లబ్ధిదారుల సెషన్',
    digitalHealthPass: 'డిజిటల్ హెల్త్ పాస్ (తల్లి మరియు బిడ్డ రక్షణ కార్డ్)',
    age: 'వయస్సు',
    guardian: 'సంరక్షకుడు / భర్త',
    location: 'గ్రామం',
    registeredAsha: 'నమోదైన ఆశా కార్యకర్త అక్క',
    emergencyHelpline: 'అత్యవసర అంబులెన్స్: 108 / 102',
    nextCheckupVaccine: 'తదుపరి ఆరోగ్య తనిఖీ / టీకా',
    latestHealthReadings: 'తాజా ఆరోగ్య కొలతలు',
    doctorPrescriptionAdvice: 'వైద్యుని మందులు మరియు సలహాలు',
    nutritiousFoods: 'పౌష్టికమైన సాంప్రదాయ స్థానిక ఆహారాలు',
    nutritiousFoodsSub: 'మీ ఆరోగ్యానికి సిఫార్సు చేయబడిన పోషక విలువలు గల స్థానిక ఆహారాలు.',
    prepTip: 'తయారీ విధానం మరియు తీసుకునే పద్ధతి',
    counselingTip: 'ఆశా పోషకాహార మార్గదర్శక సలహా',
    viewOnlyMode: 'వీక్షణకు మాత్రమే మోడ్'
  },

  // ==================== BENGALI (সম্পূর্ণ বাংলা অনুবাদ) ====================
  bn: {
    appTitle: 'আশা (AASHA)',
    appSub: 'জাতীয় গ্রামীণ স্বাস্থ্য মিশন • ডিজিটাল স্বাস্থ্যসেবা',
    offlineBadge: 'সম্পূর্ণ অফলাইনে কাজ করে (ইন্টারনেট ছাড়া)',
    onlineBadge: 'অনলাইন মোড',
    offlineMode: 'অফলাইন মোড',
    allSynced: 'সমস্ত তথ্য নিরাপদে সিঙ্ক করা হয়েছে',
    pendingSync: 'অপেক্ষমাণ সিঙ্ক ডেটা',
    logout: 'লগআউট',
    resetSeed: 'ডেটা রিসেট করুন',
    close: 'উইন্ডো বন্ধ করুন',
    save: 'পরিবর্তন সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    back: 'ড্যাশবোর্ডে ফিরে যান',
    searchPlaceholder: 'নাম, রোগী আইডি দিয়ে খুঁজুন...',
    viewDetails: 'বিস্তারিত দেখুন',
    openTimeline: 'সম্পূর্ণ স্বাস্থ্য ইতিহাস খুলুন',
    recordVitals: 'স্বাস্থ্য পরিমাপ রেকর্ড করুন',
    scheduled: 'নির্ধারিত',
    active: 'সক্রিয়',
    months: 'মাস',
    weeks: 'সপ্তাহ',
    days: 'দিন',
    years: 'বছর',

    // Clinical & Vitals Translated
    bloodPressure: 'রক্তচাপ (ব্লাড প্রেশার)',
    systolicBp: 'সিস্টোলিক রক্তচাপ',
    diastolicBp: 'ডায়াস্টোলিক রক্তচাপ',
    hemoglobin: 'হিমোগ্লোবিন স্তর',
    bloodSugar: 'খালি পেটে রক্তের শর্করা (সুগার)',
    weight: 'ওজন (কেজি)',
    height: 'উচ্চতা / দৈর্ঘ্য (সেমি)',
    pulse: 'নাড়ির গতি (পালস)',
    fundalHeight: 'জরায়ুর উচ্চতা (ফান্ডাল হাইট)',
    temperature: 'শারীরিক তাপমাত্রা (°C)',
    gestationalAge: 'গর্ভকালীন সময়কাল',
    eddLabel: 'প্রসবের সম্ভাব্য তারিখ (EDD)',
    lmpLabel: 'শেষ মাসিকের তারিখ (LMP)',
    abhaId: 'আভা ডিজিটাল স্বাস্থ্য আইডি (ABHA ID)',
    ifaTablets: 'আয়রন ফলিক অ্যাসিড (IFA) ট্যাবলেট',
    calciumTablets: 'ক্যালসিয়াম ট্যাবলেট',
    ancCheckup: 'প্রসবপূর্ব স্বাস্থ্য পরীক্ষা (ANC)',
    vaccination: 'টিকাদান ও রোগ প্রতিরোধ',

    // Login Page
    loginTagline: 'নিরাপদ স্বাস্থ্য লগইন পোর্টাল',
    loginHeading: 'সাইন ইন করতে আপনার ভূমিকা নির্বাচন করুন',
    loginSubheading: 'লগইন শংসাপত্র লিখতে নিচে আপনার বিভাগে ক্লিক করুন।',
    ashaTitle: 'আশা কর্মী',
    ashaSubtitle: 'গ্রামীণ স্বাস্থ্য সহায়িকা পোর্টাল',
    ashaDesc: 'রোগী নিবন্ধন, মাঠপর্যায়ে স্বাস্থ্য পরীক্ষা ও গৃহ পরিদর্শন ব্যবস্থাপনা।',
    ashaBadge: 'অ্যাক্সেস: নতুন নিবন্ধন + স্বাস্থ্য পরিমাপ',
    doctorTitle: 'চিকিৎসা কর্মকর্তা',
    doctorSubtitle: 'ডাক্তার ক্লিনিক্যাল পোর্টাল',
    doctorDesc: 'উচ্চ ঝুঁকি নজরদারি, তথ্য সম্পাদনা, রোগ নির্ণয় ও প্রেসক্রিপশন।',
    doctorBadge: 'অ্যাক্সেস: সম্পূর্ণ সম্পাদনা অনুমতি',
    patientTitle: 'রোগী পোর্টাল',
    patientSubtitle: 'ব্যক্তিগত স্বাস্থ্য পাস',
    patientDesc: 'ডিজিটাল হেলথ কার্ড, মাসে শিশুর টিকা এবং পুষ্টি নির্দেশিকা।',
    patientBadge: 'অ্যাক্সেস: এক আইডি এক লগইন (শুধুমাত্র দেখার জন্য)',
    modalAshaTitle: 'আশা কর্মী লগইন',
    modalAshaSubtitle: 'আপনার আশা আইডি এবং উপ-স্বাস্থ্য কেন্দ্র পিন লিখুন',
    modalDoctorTitle: 'চিকিৎসা কর্মকর্তা লগইন',
    modalDoctorSubtitle: 'আপনার মেডিকেল রেজিস্ট্রেশন নম্বর এবং পিন লিখুন',
    modalPatientTitle: 'রোগী অনন্য পরিচয় লগইন',
    modalPatientSubtitle: 'আপনার রোগী আইডি / আভা আইডি এবং পাসকোড লিখুন (এক আইডি = এক লগইন)',
    idPlaceholderAsha: 'যেমন ASHA-VNS-04',
    idPlaceholderDoc: 'যেমন DOC-UP-88',
    idPlaceholderPatient: 'যেমন PAT-PW-101, PAT-INF-201, PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'পোর্টালে প্রবেশ করুন',
    ashaLabel: 'আশা আইডি / মোবাইল নম্বর *',
    pinLabelAsha: 'উপ-কেন্দ্র নিরাপত্তা পিন *',
    docLabel: 'মেডিকেল রেজিস্ট্রেশন নম্বর *',
    pinLabelDoc: 'হাসপাতাল নিরাপত্তা পাসকোড *',
    patientLabel: 'অনন্য রোগী আইডি / আভা আইডি / মোবাইল *',
    pinLabelPatient: 'নিরাপত্তা পাসকোড / পিন *',
    footerText: 'আশা • জাতীয় স্বাস্থ্য মিশন ও স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রণালয়',

    // ASHA Dashboard
    ashaWelcome: 'স্বাগতম',
    assignedArea: 'বরাদ্দকৃত গ্রাম এলাকা',
    registerNewPatient: '+ নতুন রোগী নিবন্ধন করুন',
    totalBeneficiaries: 'মোট নিবন্ধিত সুবিধাভোগী',
    pregnantLady: 'গর্ভবতী মহিলা',
    infants: 'শিশু (০-৫ বছর)',
    elderlyPeople: 'বয়োজ্যেষ্ঠ নাগরিক',
    viewAllRecords: 'সব রেকর্ড দেখুন',
    ancMaternalDetails: 'প্রসবপূর্ব পরীক্ষা (ANC 1-4) ও মাতৃ সুরক্ষা',
    ageInMonthsVaccines: 'মাসে বয়স ও সম্পূর্ণ টিকাদান',
    bpDiabetesDetails: 'রক্তচাপ ও ডায়াবেটিস নজরদারি',
    dailyReminders: 'দৈনিক কাজের তালিকা ও গৃহ পরিদর্শন',
    popupPregnantTitle: 'গর্ভবতী মায়েদের তালিকা (মাতৃ স্বাস্থ্য)',
    popupInfantTitle: 'শিশু ও টিকাদান তালিকা (বৃদ্ধি পর্যবেক্ষণ)',
    popupElderlyTitle: 'বয়স্কদের স্বাস্থ্য তালিকা (দীর্ঘস্থায়ী রোগ ও যত্ন)',
    popupAllTitle: 'সমস্ত নিবন্ধিত গ্রামীণ সুবিধাভোগী',

    // Doctor Dashboard
    doctorWelcome: 'মেডিকেল অফিসার ড্যাশবোর্ড',
    prioritySurveillance: 'অগ্রাধিকার নজরদারি',
    highRiskCases: 'উচ্চ ঝুঁকিপূর্ণ রোগী',
    highRiskQueueTitle: 'উচ্চ ঝুঁকিপূর্ণ রোগী ক্লিনিক্যাল নজরদারি তালিকা',
    priorityReview: 'ডাক্তারের জরুরি পর্যালোচনা প্রয়োজন',
    phcRegistryTitle: 'প্রাথমিক স্বাস্থ্য কেন্দ্র (PHC) রোগী রেজিস্ট্রি',
    phcRegistrySub: 'ক্লিনিক্যাল তথ্য সম্পাদনা, ঝুঁকি শ্রেণীকরণ এবং প্রেসক্রিপশন পরিবর্তন।',
    editDataBtn: 'তথ্য সম্পাদনা করুন',
    viewFileBtn: 'ফাইল দেখুন',
    doctorOrderLabel: 'ডাক্তারের সক্রিয় প্রেসক্রিপশন ও পরামর্শ',

    // Patient Dashboard
    loggedInAs: 'লগইন করা অ্যাকাউন্ট',
    verifiedSession: 'যাচাইকৃত সুবিধাভোগী সেশন',
    digitalHealthPass: 'ডিজিটাল হেলথ পাস (মা ও শিশু সুরক্ষা কার্ড)',
    age: 'বয়স',
    guardian: 'অভিভাবক / স্বামী',
    location: 'গ্রামের অবস্থান',
    registeredAsha: 'নিবন্ধিত আশা কর্মী দিদি',
    emergencyHelpline: 'জরুরি অ্যাম্বুলেন্স সেবা: ১০৮ / ১০২',
    nextCheckupVaccine: 'পরবর্তী নির্ধারিত পরীক্ষা / টিকা',
    latestHealthReadings: 'সাম্প্রতিক স্বাস্থ্য পরিমাপ',
    doctorPrescriptionAdvice: 'ডাক্তারের পরামর্শ ও প্রেসক্রিপশন',
    nutritiousFoods: 'পুষ্টিকর ও সহজলভ্য দেশীয় খাবার',
    nutritiousFoodsSub: 'আপনার স্বাস্থ্যের জন্য প্রস্তাবিত ঐতিহ্যবাহী পুষ্টিকর খাবার।',
    prepTip: 'প্রস্তুতি ও সেবন বিধি',
    counselingTip: 'আশা দিদির পুষ্টি পরামর্শ',
    viewOnlyMode: 'শুধুমাত্র দেখার মোড'
  },

  // ==================== MARATHI (संपूर्ण मराठी अनुवाद) ====================
  mr: {
    appTitle: 'आशा (AASHA)',
    appSub: 'राष्ट्रीय ग्रामीण आरोग्य अभियान • डिजिटल आरोग्य प्रणाली',
    offlineBadge: 'इंटरनेटशिवाय पूर्णपणे ऑफलाइन कार्यरत',
    onlineBadge: 'ऑनलाइन मोड',
    offlineMode: 'ऑफलाइन मोड',
    allSynced: 'सर्व डेटा सुरक्षितपणे सिंक झाला आहे',
    pendingSync: 'प्रलंबित सिंक डेटा',
    logout: 'लॉगआउट',
    resetSeed: 'डेटा रीसेट करा',
    close: 'विंडो बंद करा',
    save: 'बदल जतन करा',
    cancel: 'रद्द करा',
    back: 'डॅशबोर्डवर परत जा',
    searchPlaceholder: 'नाव, पेशंट आयडीने शोधा...',
    viewDetails: 'तपशील पहा',
    openTimeline: 'संपूर्ण आरोग्य इतिहास उघडा',
    recordVitals: 'आरोग्य तपासणी नोंदवा',
    scheduled: 'नियोजित',
    active: 'सक्रिय',
    months: 'महिने',
    weeks: 'आठवडे',
    days: 'दिवस',
    years: 'वर्षे',

    // Clinical & Vitals Translated
    bloodPressure: 'रक्तदाब (ब्लड प्रेशर)',
    systolicBp: 'सिस्टोलिक रक्तदाब',
    diastolicBp: 'डायस्टोलिक रक्तदाब',
    hemoglobin: 'हिमोग्लोबिन पातळी',
    bloodSugar: 'उपाशीपोटी रक्तातील साखर (शुगर)',
    weight: 'वजन (किलो)',
    height: 'उंची / लांबी (सेमी)',
    pulse: 'नाडीचे ठोके (पल्स)',
    fundalHeight: 'गर्भाशयाची उंची (फंडल हाईट)',
    temperature: 'शारीरिक तापमान (°C)',
    gestationalAge: 'गर्भधारणेचा कालावधी',
    eddLabel: 'प्रसूतीची अंदाजित तारीख (EDD)',
    lmpLabel: 'शेवटच्या मासिक पाळीची तारीख (LMP)',
    abhaId: 'आभा डिजिटल आरोग्य ओळखपत्र (ABHA ID)',
    ifaTablets: 'आयर्न फॉलिक ॲसिड (IFA) गोळ्या',
    calciumTablets: 'कॅल्शियमच्या गोळ्या',
    ancCheckup: 'प्रसूतीपूर्व आरोग्य तपासणी (ANC)',
    vaccination: 'लसीकरण आणि प्रतिकारशक्ती',

    // Login Page
    loginTagline: 'सुरक्षित आरोग्य प्रवेश पोर्टल',
    loginHeading: 'प्रवेश करण्यासाठी आपली भूमिका निवडा',
    loginSubheading: 'लॉगिन माहिती भरण्यासाठी खालील श्रेणीवर क्लिक करा.',
    ashaTitle: 'आशा सेविका',
    ashaSubtitle: 'ग्रामीण आरोग्य सहाय्यक पोर्टल',
    ashaDesc: 'रुग्ण नोंदणी, फील्ड तपासणी आणि दैनंदिन गृहभेटी व्यवस्थापन.',
    ashaBadge: 'प्रवेश: नवीन नोंदणी + तपासणी',
    doctorTitle: 'वैद्यकीय अधिकारी',
    doctorSubtitle: 'डॉक्टर क्लिनिकल पोर्टल',
    doctorDesc: 'उच्च जोखीम देखरेख, क्लिनिकल डेटा संपादन, निदान आणि औषधोपचार.',
    doctorBadge: 'प्रवेश: संपूर्ण संपादन अधिकार',
    patientTitle: 'रुग्ण पोर्टल',
    patientSubtitle: 'वैयक्तिक आरोग्य पास',
    patientDesc: 'डिजिटल आरोग्य कार्ड, महिन्यांत बाल लसीकरण आणि पोषण आहार चार्ट.',
    patientBadge: 'प्रवेश: एक आयडी एक लॉगिन (केवळ पाहण्यासाठी)',
    modalAshaTitle: 'आशा सेविका प्रवेश',
    modalAshaSubtitle: 'आपला आशा आयडी आणि उपकेंद्र सुरक्षा पिन प्रविष्ट करा',
    modalDoctorTitle: 'वैद्यकीय अधिकारी प्रवेश',
    modalDoctorSubtitle: 'आपला वैद्यकीय नोंदणी क्रमांक आणि सुरक्षा पिन प्रविष्ट करा',
    modalPatientTitle: 'रुग्ण विशिष्ट ओळख लॉगिन',
    modalPatientSubtitle: 'आपला पेशंट आयडी / आभा आयडी आणि पिन प्रविष्ट करा (एक आयडी = एक लॉगिन)',
    idPlaceholderAsha: 'उदा. ASHA-VNS-04',
    idPlaceholderDoc: 'उदा. DOC-UP-88',
    idPlaceholderPatient: 'उदा. PAT-PW-101, PAT-INF-201, PAT-ELD-301',
    pinPlaceholder: '••••',
    signInBtn: 'पोर्टलमध्ये प्रवेश करा',
    ashaLabel: 'आशा आयडी / मोबाईल क्रमांक *',
    pinLabelAsha: 'उपकेंद्र सुरक्षा पिन *',
    docLabel: 'नोंदणी क्रमांक *',
    pinLabelDoc: 'सुरक्षा पासकोड *',
    patientLabel: 'विशिष्ट पेशंट आयडी / आभा आयडी / मोबाईल *',
    pinLabelPatient: 'सुरक्षा पासकोड / पिन *',
    footerText: 'आशा • राष्ट्रीय आरोग्य अभियान आणि आरोग्य व कुटुंब कल्याण मंत्रालय',

    // ASHA Dashboard
    ashaWelcome: 'स्वागत आहे',
    assignedArea: 'नियुक्त गाव कार्यक्षेत्र',
    registerNewPatient: '+ नवीन रुग्ण नोंदणी करा',
    totalBeneficiaries: 'एकूण नोंदणीकृत लाभार्थी',
    pregnantLady: 'गरोदर माता',
    infants: 'शिशू (०-५ वर्षे)',
    elderlyPeople: 'ज्येष्ठ नागरिक',
    viewAllRecords: 'सर्व नोंदी पहा',
    ancMaternalDetails: 'प्रसूतीपूर्व तपासणी (ANC 1-4) आणि माता सुरक्षा',
    ageInMonthsVaccines: 'महिन्यांत वय आणि संपूर्ण लसीकरण',
    bpDiabetesDetails: 'रक्तदाब आणि साखर तपासणी तपशील',
    dailyReminders: 'दैनंदिन कामे आणि गृहभेटी',
    popupPregnantTitle: 'गरोदर मातांची यादी (मातृ आरोग्य)',
    popupInfantTitle: 'शिशू व बाल लसीकरण यादी (वाढ निरीक्षण)',
    popupElderlyTitle: 'ज्येष्ठ नागरिक आरोग्य यादी (दीर्घ आजार व काळजी)',
    popupAllTitle: 'सर्व नोंदणीकृत ग्रामीण लाभार्थी यादी',

    // Doctor Dashboard
    doctorWelcome: 'वैद्यकीय अधिकारी डॅशबोर्ड',
    prioritySurveillance: 'प्राधान्य देखरेख',
    highRiskCases: 'उच्च जोखीम रुग्ण',
    highRiskQueueTitle: 'उच्च जोखीम रुग्ण तपासणी रांग',
    priorityReview: 'तातडीचे पुनरावलोकन आवश्यक',
    phcRegistryTitle: 'प्राथमिक आरोग्य केंद्र (PHC) रुग्ण नोंदवही',
    phcRegistrySub: 'क्लिनिकल डेटा संपादन, जोखीम वर्गीकरण आणि औषधोपचार बदल अधिकार.',
    editDataBtn: 'डेटा संपादित करा',
    viewFileBtn: 'फाइल पहा',
    doctorOrderLabel: 'डॉक्टरांचे सक्रिय प्रिस्क्रिप्शन आणि सूचना',

    // Patient Dashboard
    loggedInAs: 'लॉगिन केलेले खाते',
    verifiedSession: 'सत्यापित लाभार्थी सत्र',
    digitalHealthPass: 'डिजिटल आरोग्य पत्र (माता व बाल संरक्षण कार्ड)',
    age: 'वय',
    guardian: 'पालक / पती',
    location: 'गाव',
    registeredAsha: 'नोंदणीकृत आशा ताई',
    emergencyHelpline: 'तातडीची रुग्णवाहिका सेवा: १०८ / १०२',
    nextCheckupVaccine: 'पुढील तपासणी / लस',
    latestHealthReadings: 'अलीकडील आरोग्य तपासणी',
    doctorPrescriptionAdvice: 'डॉक्टरांचा सल्ला आणि औषधे',
    nutritiousFoods: 'पौष्टिक आणि परवडणारा देशी आहार',
    nutritiousFoodsSub: 'आपल्या आरोग्यासाठी शिफारस केलेले पारंपरिक पौष्टिक अन्नपदार्थ.',
    prepTip: 'बनवण्याची पद्धत आणि सेवन नियम',
    counselingTip: 'आशा पोषण मार्गदर्शन सल्ला',
    viewOnlyMode: 'केवळ पाहण्याचा अधिकार'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('aasha_language') || 'en';
  });

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem('aasha_language', langCode);
    }
  };

  const t = TRANSLATIONS[currentLang] || TRANSLATIONS.en;

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        setLanguage,
        t,
        languages: SUPPORTED_LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
